FROM golang:1.24.3

WORKDIR /app

# Copy go.mod and go.sum
COPY api/go.mod api/go.sum ./
RUN go mod download

# Install Air for hot reloading
RUN go install github.com/air-verse/air@latest

# Copy the rest of the application code
COPY api/ ./

# Create the bin directory and build the entire package
RUN mkdir -p bin && go build -o bin/main .

EXPOSE 8080

CMD ["air"]