[psql]
  dbname  = "gonotes"
  host    = "localhost"
  port    = 5432
  user    = "gonotes"
  pass    = "gonotes"
  sslmode = "disable"
  blacklist = []
  whitelist = []

# Output configuration
output   = "models"
wipe     = true
no-tests = true